version: '3'

services:
  # MySQL Database Service
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 448518
      MYSQL_DATABASE: animodb01
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always

  # Backend Service (Node.js)
  backend:
    build: ./Animo-v2-Backend
    environment:
      PORT: 8112
      NAME_DB: animodb01
      USER_DB: root
      PASS_DB: 448518
      IP_DB: db
      PORT_DB: 3306
      DIALECT_DB: mysql
      SECRET_KEY: sirfamily
      EXPIRES_IN: 1d
      CLOUDINARY_SECRET: mhnnJSrvGtD0v46nu1ATxIakR_I
    ports:
      - '8112:8112'
    depends_on:
      - db
    networks:
      - app-network
    restart: always


  # Frontend Service (React.js)
  frontend:
    build:
      context: ./Animo-v2-Frontend
    environment:
      VITE_API_URL: http://localhost:8112
    depends_on:
      - backend
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./Animo-v2-Frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Animo-v2-Frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
    networks:
      - app-network
    restart: always

    
networks:
  app-network:
    driver: bridge
